### ISSUE TITLE
Match FabMo Dashboard Color Scheme

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#10]
The color scheme of the tool minder should match that of the dashboard (use the dark blue for the top bar, the apple green for the launch buttons)

**Comment by jlucidar** [comment]
![image](https://cloud.githubusercontent.com/assets/7430482/13202285/44d52a70-d895-11e5-959e-e11ad2adb1e6.png)
better that way @ryansturmer ?
