### ISSUE TITLE
Should have a "compact" mode for situations where there are a lot of tools 

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#18]
Maybe a hamburger menu in the top bar to indicate?

**Comment by jlucidar** [comment]
what information do we _really_ want to display in the compact bar ?
- name
- state (only the color circle ? with text ? )
- mini goto button
- IP address is probably not required
- Job info ?? (it's probably too much...)

**Comment by jlucidar** [comment]
I don't think this is anymore relevant. we can reopen this as it become necessary.
