### ISSUE TITLE
Should indicate progress if there's a running file

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#19]
I think we want to steer away from having too much information in the display for each tool, since this is a tool finder and not much else, but since the progress information comes with the job progress anyway, I think it's useful, especially if you're using the minder in a shop with a bunch of tools.

**Comment by jlucidar** [comment]
progress bar or percentage ?

**Comment by ryansturmer** [comment]
I think a progress bar would be nice?

**Comment by jlucidar** [comment]
This is how it looks :) solved by commit fdfd0427ab8bced58a3650caccd548921f423584
![image](https://cloud.githubusercontent.com/assets/7430482/13332718/ae68c354-dc03-11e5-9a9a-4250951145cf.png)
