### ISSUE TITLE
"Go to that device" should open the system's default browser

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#4]
The systems default browser should be launched in the event that the "go to that device" button is pressed, rather than a new window in the internal, node-webkit world.  On windows, if that browser is found to be internet explorer, a warning dialog should be opened and the user directed to download chrome or firefox.

**Comment by jlucidar** [comment]
I think that it would be better to integrate the warning message directly in the dashboard, as its the dashboard that is not compatible with IE ... shall I open a new issue in the engine repo ?
