### ISSUE TITLE
Colorization/text based on status

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#5]
Tools in the list should be colorized based on tool status.  Green for running, orange for paused/stopped - blue for manual drive.  We can use a pastel version of the "official" red/green/orange/blue from fabmo:

For tools that are running a job, the name of the job can be indicated in text below the tool name.

I don't think we need tool position displayed here, but the job information would be nice.

![screen shot 2016-02-02 at 8 39 52 am](https://cloud.githubusercontent.com/assets/1383181/12750993/90113fea-c988-11e5-8817-68ca53b771a4.png)

**Comment by jlucidar** [comment]
feature added in the new version !
