### ISSUE TITLE
Detection logic

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#6]
Once a tool has been detected, an attempt to connect to that tool via the websocket should be made.  If a websocket connection is made, the detection tool needn't continue to perform the detection exchange with the tool, unless the websocket connection is lost.  The websocket will convey tool status information, and can be used to send commands to the tool if needed.

**Comment by jlucidar** [comment]
Ok for the websocket thing. But stopping the detection tool is not that simple as it works through udp broadcast. I still need to run that service for multi-machine finding right ?

**Comment by jlucidar** [comment]
closing this one as it doesn't seems relevant anymore.
