### ISSUE TITLE
Persistence of units in the listing

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#8]
Units should persist for a reasonable amount of time - I have observed that through the discovery process, some units appear to appear and disappear rapidly, which that's not realistic in terms of what's actually going on with the network, most likely.  If a unit is seen, it should not be considered "gone" until it hasn't been seen for at least a few consecutive iterations of the scanning process.  This way the display isn't flickering constantly with units that don't respond to every single scan.

**Comment by jlucidar** [comment]
I didn't test it with multiple tools, but the new logic is in place. I close the issue for now.
